---
title: "Mid-term exam | Data Science (S.2018)"
Student ID: null
date: "4th of june 2018"
output:
  html_document: default
  word_document: default
Name: Ana Maria Buigues Perez
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Task 1: -----

# (a) Saving and inspecting data:


```{r 1a}
sp <- as_tibble(sleep)
dim(sp)
```

# (b)

```{r}
```

# (c) Medians and raw values of extra sleep time by group

```{r 1c}
ggplot(data = sleep) + geom_bar(mapping = aes(x = extra, y = group), stat = "identity")
```

# (d)

```{r}
```

## Task 2: -----

# (a)

```{r 2a}
de <- tibble(share_2013 = c (41.5, 25.7, NA), share_2017 = c(33.0, 20.5, NA))
```

# (b)

```{r}
```

# (c)

```{r}
```

## Task 3: ----

# (a)

```{r}
```

# (b)

```{r}
```

# (c)

```{r}
```

# (d)

```{r}
```

# (e)

```{r}
```

## Task 4: ----

# (a)

```{r 4a}
```

# (b)

```{r 4b}
```

# (c)

```{r 4c}
```

# (d)

```{r}
```

## Task 5: ----

# (a) Save and inspect data:

```{r 5a}
ir <- as.tibble(iris)
ir
dim(ir)
```

# (b)

```{r}
```

# (c)

```{r}
```

# (d)

```{r}
```

# (e)

```{r}
```

# (f)

```{r}
```

# (g)

```{r}
```

# (h)

```{r}
```

# (i)

```{r}
```

## Task 6: ----

# (a)

```{r}
```

# (b)

```{r}
```

# (c)

```{r}
```

# (d)

```{r}
```

# (e)

```{r}
```

# (f)

```{r}
```

# (g)

```{r}
```

## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ##
## End of file. ----- 
