---
title: "Mid-term exam  | Data science for psychologists (Summer 2018)"
author: "Lisa-Marie Walther| Student ID: 01/946631"
date: "4 Juni 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Preparations
```{r, 1, echo = TRUE, eval = TRUE}
library(tidyverse)
```

## Task 1: 
```{r, 2, echo = TRUE, eval = TRUE}
## (a) Saving and inspecting data:
sp <- as_tibble(sleep)
dim(sp)
glimpse(sp)
# View(sleep)
?sleep

## Answer: The sleep data contains 20 rows and 3 columns. 

## (b): compute the number of observations (rows) by group and key descriptives (their mean, median, and standard deviation)

sp%>%
  group_by(group)%>%
  summarise(
    group_number = n(), 
    group_mean = mean(extra, na.rm = TRUE),
    group_median = median (extra,na.rm = TRUE),
    group_sd = sd(extra, na.rm = TRUE)
    )%>%
  print()

## (c): create a graph that shows the medians and raw values of extra sleep time by group

ggplot(sp)+
  geom_boxplot(mapping = aes(x = group, y = extra))+
  geom_jitter(mapping = aes(x = group, y = extra))+
  labs(title = "medians and raw values of extra sleep time by group")

## (d): Reformat the sleep data in sp so that the 2 groups appear in 2 lines (rows) and 10 subject IDs as 10 columns
sp%>%
  spread(key = ID, value = extra)
```


##Task 2
```{r, 3, echo = TRUE, eval = TRUE}
## (a):Create a tibble de that contains this data and the missing (?) values for all other parties so that all shares of an election add up to 100%.

de <- tibble(Party = c("CDU/CSU", "SPD", "Others"),
             `Share 2013` = c(41.5, 25.7, NA),
             `Share 2017`= c(33, 20.5, NA))
de
100 - (41.5+25.7)#32.8
100 - (33+20.5)#46.5
de %>%
  replace_na(list(`Share 2013` = 32.8, `Share 2017` = 46.5))
de

## (b): Convert your de table into a "tidy" table saved as de_2
de2 <- de%>%
  gather(`Share 2013`, `Share 2017`, key = Share, value = result)%>%
  separate(Share, into = c("x", "share"), sep = " ")%>%
  select(Party, share, result)
de2

## (c): Visualize and contrast the election results by a bar chart that contains 2 bars (representing the 2 elections) and the party's share of votes (as the proportions of each bar)
#####################################################

ggplot(de)+
  geom_bar(mapping = aes(x = share, y = ..prop.., group = 1), position = "stack")

```

##Task 3

```{r, 4, echo = TRUE, eval = TRUE}
## (a): Save the tibble dplyr::starwars as sw and report its dimensions
sw <- dplyr::starwars
is_tibble(sw)

dim(sw)
# View(sw)

##Answer: The star wars data contains 87 rows and 13 columns. 

## (b):
#How many missing (NA) values does sw contain?
sum(is.na(sw))

##Answer: sw contains 101 missing values.


#Which individuals come from an unknown (missing) homeworld but have a known birth_year or known mass? 

sw%>%
filter(is.na(homeworld), !is.na(mass) | !is.na(birth_year))
  
##(c): 
#How many humans are contained in sw overall and by gender?
#overall
sw %>%
 filter(species == "Human")%>%
  count()

## Answer: 35 Humans overall

#by gender
sw %>%
 filter(species == "Human")%>%
  group_by(gender)%>%
  count()

## Answer: 9 female, 26 male humans

#How many and which individuals in sw are neither male nor female? 
sw %>%
  group_by(gender)%>%
  count()
  

#Of which species in sw exist at least 2 different gender values?
sw %>%
  group_by(species)%>%
  summarise(gender_values = n_distinct(gender))%>%
  filter(gender_values >= 2)


##(d): 
#From which homeworld do the most indidividuals (rows) come from?
sw%>%
  group_by(homeworld)%>%
  summarise(indiv_homeworld = n())%>%
  arrange(desc(indiv_homeworld))
## Answer: From Naboo


#What is the mean height of all individuals with orange eyes from the most popular homeworld? 

sw%>%
  filter(homeworld == "Naboo", eye_color == "orange")%>%
  summarise(mean_height = mean(height, na.rm = TRUE))

## Answer: 208.667

## (e): 
#Compute the median, mean, and standard deviation of height for all droids.

sw%>%
  filter(species == "Droid")%>%
  summarise(
    meanheight_droids = mean(height, na.rm = TRUE),
     medianheight_droids = median(height, na.rm = TRUE),
     sdheight_droids = sd(height, na.rm = TRUE)
  )


#Compute the average height and mass by species and save the result as h_m. 

h_m <- sw%>%
  group_by(species)%>%
  summarise(
    mean_height_species = mean(height, na.rm = TRUE),
    mean_mass_species = mean(mass, na.rm = TRUE))
  
print(h_m)

#Sort h_m to list the 3 species with the smallest individuals (in terms of mean height). 

h_m%>%
  arrange(mean_height_species)%>%
  head(n=3)


#Sort h_m to list the 3 species with the heaviest individuals (in terms of median mass).
h_m%>%
  arrange(desc(mean_mass_species))%>%
  head(n=3)

```

##Task 4

```{r, 5, echo = TRUE, eval = TRUE}
##(a): Create a tibble st that contains this data in this (wide) format

st <- tibble(
  stock = c("Amada", "Betix", "cevis"),
  d1_start = c(2.5, 3.3, 4.2),
  d1_end = c(3.6, 2.9, 4.8),
  d2_start = c(3.5, 3.0, 4.6),
  d2_end = c(4.2, 2.1, 3.1),
  d3_start = c(4.4, 2.3, 3.2),
  d3_end = c(2.8, 2.5, 3.7)
)
st
# View(st)

##(b):Transform st into a longer table st_long that contains 18 rows and only 1 numeric variable for all stock prices. 


st_long <- st%>%
  gather(`d1_start`,`d1_end`,`d2_start`,`d2_end` , `d3_start`,`d3_end`, key = time, value = price)

st_long
dim(st_long)
#Adjust this table so that the day and time appear as 2 separate columns.
st_long <- st_long%>%
  separate(col= time, into = c("day" ,"time"), sep = "_")

st_long


##(c):Create a graph that shows the 3 stocks' end prices (on the y-axis) over the 3 days (on the x-axis)


st_long%>%
  filter(time == "end")%>%
  ggplot +
  geom_point(mapping = aes(x= day, y = price,color = stock))+
 labs(title = "stocks' end prices over the days")

## (d): Spread st_long into a wider table that contains start and end prices as 2 distinct variables (columns) for each stock and day.

st_long%>%
  spread(key = time, value = price)%>%
  select(stock, day, start, end)%>%
  arrange(day)
  
```

## Task 5

```{r, 6, echo = TRUE, eval = TRUE}

##(a):Save datasets::iris a tibble ir that contains this data and inspect it. Are there any missing values? 
ir <- as_tibble(datasets::iris)
glimpse(ir)
summary(ir)
# View(ir)
sum(is.na(ir))

##Answer: No NAs in ir

##(b):Compute a summary table that shows the means of the 4 measurement columns (Sepal.Length, Sepal.Width, Petal.Length, Petal.Width) for each of the 3 Species (in rows). Save the resulting table of means as a tibble im1 .

im1 <- ir%>%
  group_by(Species)%>%
  summarise(
    mean_sl = mean(Sepal.Length, na.rm = TRUE),
     mean_sw = mean(Sepal.Width, na.rm = TRUE),
     mean_pl = mean(Petal.Length, na.rm = TRUE),
     mean_pw = mean(Petal.Width, na.rm = TRUE))
im1

##(c):Create a histogram that shows the distribution of Sepal.Width values across all species

ggplot(ir)+
  geom_histogram(mapping = aes(x=Sepal.Width))+
  labs(title = "distribution of Sepal.Width values across all species")

##(d):Create a plot that shows the shape of the distribution of Sepal.Width values for each species. 

ggplot(ir)+
  geom_freqpoly(mapping = aes(x=Sepal.Width, color = Species))+
  labs(title = "distribution of Sepal.Width values for each species")

##(e): Create a plot that shows Petal.Width as a function of Sepal.Width separately (i.e., in 3 facets) for each species. 

ggplot(ir)+
  geom_point(mapping = aes(x = Sepal.Width, y = Petal.Width))+
  geom_smooth(mapping = aes(x = Sepal.Width, y = Petal.Width), se = FALSE)+
  facet_grid(.~Species)


##(f): Re-format your tibble ir into a tibble ir_long which in "long format"

ir %>%
  gather(`Sepal.Length`:`Petal.Width`, key = IV, value = val)%>%
  separate(IV, into = c("part", "metric"))

##(g)Use ir_long to recompute the subgroup means (for each combination of species, plant part, and metric) computed in 5b.. Save the resulting table of means as a tibble im2 and verify that they have not changed from im1 above
```

##Task 6

```{r, 7, echo = TRUE, eval = TRUE}
##(a):
data <- read_csv("http://rpository.com/ds4psy/mt/out.csv") 


data <- as_tibble(data)
glimpse(data)

##Answer: Observations: 1000, Variables: 3

##(b):How many missing data values are there in data? 

sum(is.na(data))

##Answer: 18

##(c): What is the gender (or sex) distribution in this sample?
data
data%>%
  group_by(sex)%>%
  count()
##Answer: feamle: 507, male: 493


##(d): Create a plot that shows the distribution of height values for each gender

ggplot(data)+
  geom_histogram(mapping = aes(x=height, fill = sex), position = "dodge")


##(e):
#Compute 2 new variables that signal and distinguish between 2 types of outliers in terms of height:
##1. outliers relative to the height of the overall sample (i.e., individuals with height values deviating more than 2 SD from the overall mean of height) (1 point)

data <- data%>%
  mutate(relative_outliner_1 = height < (mean(height, na.rm = TRUE)- 2* sd(height, na.rm = TRUE)) | height > (mean(height, na.rm = TRUE)+ 2* sd(height, na.rm = TRUE)))


##2. outliers relative to the height of some subgroup's mean and SD. Here, a suitable subgroup to consider is every person's gender (i.e., individuals with height values deviating more than 2 SD from the mean height of their own gender). (1 point)

mean_w <- data%>%
  filter(sex == "female")%>%
summarise(mean(height, na.rm = TRUE))

sd_w <- data%>%
  filter(sex == "female")%>%
summarise(sd(height, na.rm = TRUE))

data%>%
  filter(sex== "female")%>%
  mutate(relative_outliner_2 = height < (mean_w - 2* sd_w)| height > (mean_w + 2* sd_w))

data


```

