---
title: "Final exam  | Data science for psychologists (Summer 2018)"
author: "Lisa-Marie Walther| Student ID: 01/946631"
date: "15 July 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Preparations
```{r, 1, echo = TRUE, eval = TRUE}
library(tidyverse)
```

## Task 1: Plants
```{r, 2, echo = TRUE, eval = TRUE}
## (a):Save the PlantGrowth data as a tibble and inspect its dimensions.
plants <- as.tibble(PlantGrowth)

glimpse(plants)
View(plants)
## Answer:PlantGrowth data contains 30 cases (rows) and 2 variables (columns). 


## (b):Use a dplyr pipe to compute the number of observations (rows) in each group and some key descriptives (their mean, median, and standard deviation). 

plants%>%
  group_by(group)%>%
  summarise(n_group = n(),
            mn_group = mean(weight, na.rm = TRUE),
            mdn_group = median(weight, na.rm = TRUE),
            sd_group = sd(weight, na.rm = TRUE), 
            min_group = min(weight, na.rm = TRUE),
            max_group = max(weight, na.rm = TRUE))


## (c):Use ggplot to create a graph that shows the medians and raw values of plant weight by group.

ggplot(plants)+
  geom_boxplot(mapping = aes(x = group, y = weight, color = group))+
  geom_point(mapping = aes(x = group, y = weight, color = group))+
  labs(title = "Plant weight by group (Raw values and medians)")+
  theme_light()
```

##Task 2: Hot and wet flights

```{r, 3, echo = TRUE, eval = TRUE}
library(nycflights13)

## (a):Save the tibble nycflights13::weather as wt and report its dimensions. 

wt <- as.tibble(nycflights13::weather)

glimpse(wt)

## Answer:Data contains 26,130 observations (rows) and 15 variables (columns).  

## (b):Missing values and known unknowns:
#How many missing (NA) values does wt contain? 
sum(is.na(wt))

##Answer: 3157

#What is the percentage of missing (NA) values in wt? 
#Amount cells
26130*15 #391950

3157/391950 #0.008054599

## Answer: ~0.0081%

#What is the range (i.e., minimum and maximum value) of the year variable? 

wt%>%
  select(year)%>%
  summarise(min_year = min(year, na.rm = TRUE),
            max_year = max(year, na.rm = TRUE))

## Answer: 2013

## (c):How many observations (rows) does the data contain for each of the 3 airports (origin)? 

wt%>%
  group_by(origin)%>%
  count()
  
## Answer: 
#EWR	8708			
#JFK	8711			
#LGA	8711

## (d):Compute a new variable temp_dc that provides the temperature (in degrees Celsius) that corresponds to temp (in degrees Fahrenheit).
#Hints: The formula for conversion from Fahrenheit (degrees F) to Celsius (degrees C) is: C=(F-32)× 5/9

wt%>%
  mutate(temp_dc = (temp - 32)*5/9)

#Add your new temp_dc variable to a new dataset wt_2 and re-arrange its columns so that your new temp_dc variable appears next to temp.
wt_2 <- wt%>%
  mutate(temp_dc = (temp - 32)*5/9)%>%
  select(origin, year, month, day, hour, temp, temp_dc, everything())
##Check: 
wt_2

## (e):When only considering “JFK” airport:
#What are the 3 (different) dates with the (a) coldest and (b) hottest temperatures at this airport?
#Report the 3 dates and their extreme temperatures (in degrees Celsius) for (a) and (b). 
wt_2%>%
  filter(origin == "JFK")%>%
  group_by(year, month, day)%>%
  arrange(temp)

## ANswer: (a): coldest: 23.1.2013 (12.02°F, -11.1°C), 24.1.2013(12.92°F, -10.6°C), 9.5.2013(13.10°F, -10.5°C)

wt_2%>%
  filter(origin == "JFK")%>%
  group_by(year, month, day)%>%
  arrange(desc(temp))


#Answer: (b): hottest: 18.7.2013 (98.06°F, 36.7°C), 16.7.2013 (96.08°F, 35.6°C), 15.7.2013 (95.0°F, 35.0°C)

## (f):Plot the amount of mean precipitation by month for each of the 3 airports (origin). 
#Hint: First use dplyr to compute a table of means (by origin and month). Then use ggplot to draw a line or bar plot of the means.
wt_2

tab <- wt_2%>%
  select(precip, origin, month)%>%
  group_by(origin, month)%>%
  summarise(mn_precip = mean(precip, na.rm = TRUE))

ggplot(tab)+
  geom_point(mapping = aes(x = month, y = mn_precip, color = origin, shape = origin), size = 3)+
  geom_line(mapping = aes(x = month, y = mn_precip, color = origin))+
   labs(title = "Mean Percipitation per month", y= "Mean percipitation", x = "Month")+
  theme_light()

## (g):For each of the 3 airports:
#When excluding extreme cases of precipitation (specifically, values of precip greater than 0.30):

wt_3 <- wt_2%>%
  select(precip, origin, month)%>%
  filter(precip <= 0.3)%>%
  mutate(summer = (month == 4 |month == 5|month == 6|month == 7|month == 8|month == 9))



#Does it rain more during winter months (Oct to Mar) or during summer months (Apr to Sep)? 

tab_2 <- wt_3%>%
  group_by(summer, origin)%>%
  summarise(precip_sum = sum(precip))
##Answer: EWR: more in summer
      #   JFK: more in winter
      #   LGA: more in winter 

#Plot the total amount of precipitation in winter vs. summer for each airport. 

ggplot(tab_2)+
  geom_bar(mapping = aes(x = summer, y = precip_sum, fill = summer), stat = "identity")+
  facet_grid(.~origin)+
  labs(title = "Precipitation summer vs. winter", x = "summer?", y = "Precipitation")+
  theme_light()
```

##Task 3: Numeracy vs. intelligence

```{r, 4, echo = TRUE, eval = TRUE}
## Load data  
data <- read_csv("http://rpository.com/ds4psy/data/numeracy.csv")
data
## (a):Inspect the data dimensions and the percentage of missing values.

glimpse(data)#1000 cases, 12 variables

sum(is.na(data))#130

130/(1000*12) #0.01083333

##Answer: 1,08 % of values are missing

## (b):Split the birth date (bdate) variable into 3 separate variables (byear, bmonth, and bday) that denote the year, month, and day of each participant’s birth.

data <- data%>%
  separate(bdate, into = c("byear", "bmonth", "bday"), sep = "-", convert = TRUE, remove = FALSE)
data

## (c): Create a new variable summer_born that is TRUE when a participant was born in summer (defined as April to September) and FALSE when a person was born in winter (October to March). 

data <- data%>%
  mutate(summer_born = (bmonth == 4 |bmonth == 5 |bmonth == 6|bmonth == 7|bmonth == 8|bmonth == 9))

## (d):Compute the current age of each participant as the person would report it (i.e., in completed years, taking into account today’s date). 

data <- data%>%
  mutate(pre_age = (bmonth >=7 & bday > 15))

data%>%
  mutate(age = ifelse(pre_age == "TRUE", 2018-byear-1, 2018-byear))%>%
  select(byear, age, pre_age)

## (e):List the frequency of each blood type (blood_type) by gender (as a tibble by using dplyr) and re-format your tibble into a wider format (by using tidyr) that lists the types of gender in rows and the types of blood_type as columns.

d1 <- data%>%
  group_by(blood_type, gender)%>%
  count()

d1

d2 <- spread(d1, blood_type, n)

d2


## (f):Compute descriptives (the counts, means, and standard deviations) of height (a) by gender and (b) by cohort (i.e., the decade of birth). 
#Hints: Use integer division on each participant’s age to determine his or her decade cohort: cohort = age %/% 10.
data <- data%>%
  mutate(cohort = byear %/% 10)

data%>%
  group_by(gender, cohort)%>%
  summarise(n = n(),
            mn_height = mean(height, na.rm = TRUE),
            sd_height = sd(height, na.rm = TRUE))

d3 <- data%>%
  group_by(gender)%>%
  summarise(n = n(),
            mn_height = mean(height, na.rm = TRUE),
            sd_height = sd(height, na.rm = TRUE))

d4 <- data%>%
  group_by( cohort)%>%
  summarise(n = n(),
            mn_height = mean(height, na.rm = TRUE),
            sd_height = sd(height, na.rm = TRUE))


## (g):Visualize the distributions of height (a) by gender and (b) by cohort. What do you find? 

ggplot(data)+
  geom_histogram(mapping = aes(x = height, fill = gender), position = "dodge", binwidth = 5)+
  labs(title = "Distribution of height")
  theme_light()
  
data$cohort <- as.character(data$cohort)

ggplot(data)+
  geom_histogram(mapping = aes(x = height, fill = cohort), position = "dodge", binwidth = 5)+
  labs(title = "Distribution of height")
  theme_light()


## (h): Compute the aggregate BNT score as the sum of all four bnt_i values (i.e., a value varying from 0 to 4) for each participant. How many missing BNT values are there? 
  
  data <- data%>%
    mutate(bnt_total = (bnt_1 + bnt_2 + bnt_3 + bnt_4))

  sum(is.na(data$bnt_total)) #78 missings
##total scores are NA if at least one score is missing
  
## (i):Inspect the values for the 2 intelligence scores g_iq and s_iq:
  
#How many missing values are there?
  
sum(is.na(data$g_iq)) #20
sum(is.na(data$s_iq)) #30
  
#What are their means and their ranges (minimum and maximum values)?
summary(data$g_iq)#min: 73.00 , max:  139.00

summary(data$s_iq)#min: 70.00 , max:  131.00
   
#Plot their distributions in 2 separate histograms.
ggplot(data)+
  geom_histogram(mapping = aes(x = g_iq), binwidth = 2, fill = "darkgreen")+
  labs(title = "Distribution of g - intellegence scores")+
  theme_light()

ggplot(data)+
  geom_histogram(mapping = aes(x = s_iq), binwidth = 2, fill = "darkblue")+
  labs(title = "Distribution of s - intellegence scores")+
  theme_light()

## (j):Visualize the relationship between g_iq and s_iq. Can you detect any systematic trend? 
ggplot(data)+
  geom_point(mapping = aes(x = s_iq, y = g_iq), color = "darkblue", alpha = 0.2, size = 2)+
  geom_smooth(mapping = aes(x = s_iq, y = g_iq), se = FALSE)
  labs(title = "Relationship between g_iq and s_iq")+
  theme_light()

## (k):Does numeracy (as measured by the aggregate BNT score) seem to vary by gender?

ggplot(data)+
  geom_bar(mapping = aes(x = bnt_total, fill = gender), position = "dodge")+
  labs(title = "Distribution bnt_total per gender")+
  theme_light()

##Answer: Seems to vary a little bit per gender

## (l):Assess possible effects of numeracy (as measured by BNT) on the 2 measures of intelligence (g_iq and s_iq). 

ggplot(data)+
  geom_point(mapping = aes(x = s_iq, y = g_iq), color = "darkblue", alpha = 0.2, size = 2)+
  labs(title = "Relationship between g_iq and s_iq")+
  theme_light()+
  facet_grid(.~bnt_total)

## (m):Assess possible effects of the independent variables
#gender (gender),
#age (as provided by age or cohort from above),
#birth season (summer_born),
#blood type (blood_type), and
#the day of the week on which a person was born (bweekday),


###on each of the 2 types of intelligence (g_iq and s_iq) in 2 ways:
#numercially (by computing group means) and
#graphically (by plotting means and/or distributions).
#Which plausible or implausible effects does the data suggest?

###numerically###


data%>%
  group_by(gender)%>%
  summarise(mn_gender_g = mean(g_iq, na.rm = TRUE),
            mn_gender_s = mean(s_iq, na.rm = TRUE))


data%>%
  group_by(cohort)%>%
  summarise(mn_cohort_g = mean(g_iq, na.rm = TRUE),
            mn_cohort_s = mean(s_iq, na.rm = TRUE))


data%>%
  group_by(summer_born)%>%
  summarise(mn_summer_born_g = mean(g_iq, na.rm = TRUE),
            mn_summer_born_s = mean(s_iq, na.rm = TRUE))


data%>%
  group_by(blood_type)%>%
  summarise(mn_blood_type_g = mean(g_iq, na.rm = TRUE),
            mn_blood_type_s = mean(s_iq, na.rm = TRUE))


data%>%
  group_by(bweekday)%>%
  summarise(mn_bweekday_g = mean(g_iq, na.rm = TRUE),
            mn_bweekday_s = mean(s_iq, na.rm = TRUE))

###graphically###

ggplot()+
  geom_jitter(data, mapping = aes(x = s_iq, y = g_iq), color = "darkblue", alpha = 0.2, size = 2)+
  geom_smooth(data, mapping = aes(x = s_iq, y = g_iq), se = FALSE)+
  facet_grid(.~gender)+
  labs(title = "G-IQ, S-IQ and gender")+
  theme_light()


ggplot()+
  geom_jitter(data, mapping = aes(x = s_iq, y = g_iq), color = "darkblue", alpha = 0.2, size = 2)+
  geom_smooth(data, mapping = aes(x = s_iq, y = g_iq), se = FALSE)+
  facet_grid(.~cohort)+
  labs(title = "G-IQ, S-IQ and cohort")+
  theme_light()

ggplot()+
  geom_jitter(data, mapping = aes(x = s_iq, y = g_iq), color = "darkblue", alpha = 0.2, size = 2)+
  geom_smooth(data, mapping = aes(x = s_iq, y = g_iq), se = FALSE)+
  facet_grid(.~summer_born)+
  labs(title = "G-IQ, S-IQ and summer born ")+
  theme_light()

ggplot()+
  geom_jitter(data, mapping = aes(x = s_iq, y = g_iq), color = "darkblue", alpha = 0.2, size = 2)+
  geom_smooth(data, mapping = aes(x = s_iq, y = g_iq), se = FALSE)+
  facet_grid(.~blood_type)+
  labs(title = "G-IQ, S-IQ and blood type")+
  theme_light()


ggplot()+
  geom_jitter(data, mapping = aes(x = s_iq, y = g_iq), color = "darkblue", alpha = 0.2, size = 2)+
  geom_smooth(data, mapping = aes(x = s_iq, y = g_iq), se = FALSE)+
  facet_grid(.~bweekday)+
  labs(title = "G-IQ, S-IQ and weekday born")+
  theme_light()
```

##Task 4: Your data, your plot

```{r, 5, echo = TRUE, eval = TRUE}
library(help = "datasets")

phones <- as_tibble(WorldPhones)
?WorldPhones
#number of telephones in various regions of the world (in thousands)

glimpse(phones)

#add year variable
year <- c(1951, 1956, 1957, 1958, 1959, 1960, 1961)

phones$year <- year

phones <- phones%>%
  select (year, everything())
phones

#total number of telephones by year
phones2 <- phones%>%
  mutate(total = N.Amer + Europe + Asia + S.Amer + Oceania + Africa + Mid.Amer)
phones2

#plot total number of telephones per year
ggplot(phones2)+
  geom_point(mapping = aes(x=year, y=total), size = 2, color = "darkblue")+
  geom_line(mapping = aes(x=year, y=total))+
  labs(title="Total increase in telephones")+
  theme_light()



##Transform tibble
phones3 <- phones%>%
  gather(N.Amer, Europe, Asia, S.Amer, Mid.Amer, Oceania, Africa,  key = "Continent", value = "count")


#Plot number of telefones per country per year
plot2 <- phones3%>%
  group_by(Continent)

 ggplot(plot2)+
   geom_point(mapping = aes(x = year, y = count, color = Continent), size = 2)+
   geom_line(mapping = aes(x = year, y = count, color = Continent))+
   labs(title = "Yearly number in telephones per year", x = "year", y = "Number")

```

By submitting this script I assure that I have completed this script by myself (using only permissible sources of help). 

 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 End of file. 
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
