---
title: "Mid-term exam  | Data science for psychologists (Summer 2018)"
author: "Name: Alisa Auer | Student ID: 01/945854"
date: "4 Juni 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preparation
```{r 1, echo = TRUE, eval = TRUE}
library(tidyverse)
pt <- 0 # initialize point score
```

# Task 1: Time to sleep

```{r 2, echo = TRUE, eval = TRUE}
?sleep
View(sleep)

# (a) Save the sleep data as a tibble sp and inspect its dimensions. 
is.tibble(sleep)
sp <- as_tibble(sleep)
is.tibble(sp) 

glimpse(sp)
dim(sp)

## Answer: The sleep data contains 20 rows and 3 columns. 

########################################################

# (b) Use a dplyr pipe to compute the number of observations (rows) by group and key descriptives (their mean, median, and standard deviation). 
sp %>%
  group_by(group) %>%
  summarise(Observations = n(),
            mean = mean(extra, na.rm = TRUE),
            median = median(extra, na.rm = TRUE),
            sd = sd(extra, na.rm = TRUE))

#########################################################

# (c) Use ggplot to create a graph that shows the medians and raw values of extra sleep time by group.
ggplot(sp, mapping = aes(x = group, y = extra, color = group)) +
  geom_boxplot() +
  geom_jitter() +
  ggtitle("Median and raw values of extra sleep time by group")

#########################################################

# (d) Reformat the sleep data in sp so that the 2 groups appear in 2 lines (rows) and 10 subject IDs as 10 columns. 
sp_reformat <- spread(sleep, key = ID, value = extra)
sp_reformat


pt <- (pt + 6) # well done! 
```

Well done!

# Task 2: Party plots

```{r 3, echo = TRUE, eval = TRUE}
# (a) Create a tibble de that contains this data and the missing (?) values for all other parties so that all shares of an election add up to 100%.
(de <- tibble(`Party` = c("CDU/CSU", "SPD", "AfD", "FDP", "DIE LINKE", "GRUENE", "CSU", "Sonstige"),
              `Share 2013` = c(34.1, 25.7, 4.7, 4.8, 8.6, 8.4, 7.4, 6.3),
              `Share 2017` = c(26.8, 20.5, 12.6, 10.7, 9.2, 8.9, 6.2, 5.1)))

sum(de$`Share 2013`)
sum(de$`Share 2017`)

#########################################################

# (b) Convert your de table into a "tidy" table saved as de_2
(de_2 <- gather(de, `Share 2013`, `Share 2017`, key = "election_year", value = "election_results"))

# Note: Use separate to split election_year into 2 columns. 

#########################################################

# (c) Visualize and contrast the election results by a bar chart that contains 2 bars (representing the 2 elections) and the party's share of votes (as the proportions of each bar). 
ggplot(de_2, mapping = aes(x = election_year, fill = Party, position = "stack"))+
  geom_bar()

# Note: Use stat = "identity" to print the value of election_results. 

pt <- (pt + 5 + 1) # 1 Bonus point for incoporating other parties (only 3 were required).  
```


# Task 3: R wars

```{r 4, echo = TRUE, eval = TRUE}
?starwars
# View(starwars)

# (a) Save the tibble dplyr::starwars as sw and report its dimensions.
sw <- starwars
glimpse(sw)

## Answer: The starwars data contains 87 rows and 13 columns.

#########################################################

# (b) Missing values and known unknowns:

  #How many missing (NA) values does sw contain?
sum(is.na(sw))

##Answer: sw contains 101 missing values

  #Which individuals come from an unknown (missing) homeworld but have a known birth_year or known  mass? 
starwars %>%
  filter(is.na(homeworld), !is.na(birth_year), !is.na(mass))

##Answer: Yoda, IG-88, Qui-Gon Jinn

#########################################################

# (c) Gender issues:

  #How many humans are contained in sw overall and by gender? 
sw %>%
  filter(species == "Human") %>%
  count()

##Answer: Overall 35 Humans

sw %>%
  filter(species == "Human") %>%
  group_by(gender) %>%
  count()

##Answer: female = 9, male = 26

# How many and which individuals in sw are neither male nor female? 
unique(sw$gender)

sw %>%
  filter(gender != "male", gender != "female") %>%
  group_by(gender) %>%
  count()

## Answer: hermaphrodite = 1, none = 2

# Of which species in sw exist at least 2 different gender values? 



#########################################################

# (d) Popular homes and heights:

# From which homeworld do the most indidividuals (rows) come from? 
sw %>%
  group_by(homeworld) %>%
  summarise(count = n()) %>%
  arrange(desc(count))

## Answer: From Naboo do the most individuals come from.

  #What is the mean height of all individuals with orange eyes from the most popular homeworld? (1 point)
sw %>%
  filter(eye_color == "orange", homeworld == "Naboo") %>%
  summarize(mean_height = mean(height, na.rm = TRUE))
  
##Answer: mean height = 208.6667

#########################################################

# (e) Seize and mass issues:

  #Compute the median, mean, and standard deviation of height for all droids.
sw %>%
  filter(species == "Droid") %>%
  summarise(median_height = median(height, na.rm = TRUE),
            mean_height = mean(height, na.rm = TRUE),
            sd_height = sd(height, na.rm = TRUE))

# Compute the average height and mass by species and save the result as h_m. 
(h_m <- sw %>%
    group_by(species) %>%
    summarise(avg_height = mean(height, na.rm = TRUE),
              avg_mass = mean(mass, na.rm = TRUE)))

# Sort h_m to list the 3 species with the smallest individuals (in terms of mean height). 
h_m %>%
  arrange(avg_height)

# Sort h_m to list the 3 species with the heaviest individuals (in terms of median mass). 
h_m %>%
  arrange(desc(avg_mass))

pt <- (pt + 11) # Well done.
```


# Task 4: Taking stocks

```{r 5, echo = TRUE, eval = TRUE}
# (a) Create a tibble st that contains this data in this (wide) format. 
(st <- tibble(`stock` = c("Amada", "Betix", "Cevis"),
              `d1_start` = c(2.5, 3.3, 4.3),
              `d1_end` = c(3.6, 2.9, 4.8),
              `d2_start` = c(3.5, 3.0, 4.6),
              `d2_end` = c(4.2, 2.1, 3.1),
              `d3_start` = c(4.4, 2.3, 3.2),
              `d3_end` = c(2.8, 2.5, 3.7)))

############################################################

# (b) Transform st into a longer table st_long that contains 18 rows and only 1 numeric variable for all stock prices. Adjust this table so that the day and time appear as 2 separate columns.
gather(st, `d1_start`, `d1_end`, `d2_start`, `d2_end`, `d3_start`, `d3_end`, key = time, value = stock_price)

# Good, but simpler solution:
st %>% 
  gather(d1_start:d3_end, key = time, value = stock_price)

############################################################

# c. Create a graph that shows the 3 stocks' end prices (on the y-axis) over the 3 days (on the x-axis).


pt <- (pt + 3) # good.
```


# Task 5: Flower Power

```{r 6, echo = TRUE, eval = TRUE}
# ?iris
# View(iris)

# (a) Save datasets::iris a tibble ir that contains this data and inspect it. Are there any missing values? 
ir <- as_tibble(iris)
sum(is.na(iris))

## Answer: keine fehlenden Werte

#############################################################

# (b) Compute a summary table that shows the means of the 4 measurement columns (Sepal.Length, Sepal.Width,  Petal.Length, Petal.Width) for each of the 3 Species (in rows). Save the resulting table of means as a tibble im1 . 
summary(iris)

im1 <- iris %>%
  group_by(Species) %>%
  summarise(mean_sl = mean(Sepal.Length),
            mean_sw = mean(Sepal.Width),
            mean_pl = mean(Petal.Length),
            mean_pw = mean(Petal.Width))

is.tibble(im1)
im1

#############################################################

# (c) Create a histogram that shows the distribution of Sepal.Width values across all species
ggplot(iris, mapping = aes(x = Sepal.Width)) +
  geom_histogram() +
  ggtitle("distribution of Sepal.Width values across all species")

#############################################################

# (d) Create a plot that shows the shape of the distribution of Sepal.Width values for each species.
ggplot(iris, mapping = aes(x = Sepal.Width, color = Species)) +
  geom_freqpoly() +
  ggtitle("distribution of Sepal.Width values for each species")

###############################################################

# (e) Create a plot that shows Petal.Width as a function of Sepal.Width separately (i.e., in 3 facets) for each species. 
ggplot(iris, mapping = aes(x = Sepal.Width, y = Petal.Width)) +
  geom_point() +
  facet_grid(Species ~ .)

#################################################################

# (f) Re-format your tibble ir into a tibble ir_long which in "long format".

pt <- (pt + 6) # very good.
```

# Task 6: Not all outliers are alike

```{r 7, echo = TRUE, eval = TRUE}
# data <- read_csv("out.csv")
# View(data)
data <- read_csv("http://rpository.com/ds4psy/mt/out.csv")  # from online source

#(a) Save the data into a tibble data and report its number of observations and variables.
is.tibble(data)
glimpse(data)

## Answer: The data contains 1000 rows and 3 columns

######################################################

#(b) How many missing data values are there in data
sum(is.na(data))

##Answer: 18 missing values

#######################################################

#(c) What is the gender (or sex) distribution in this sample? 
data %>%
  group_by(sex) %>%
  count()

## Answer: female = 507, male = 493

#####################################################

#(d) Create a plot that shows the distribution of height values for each gender. 
ggplot(data, mapping = aes(x = height, fill = sex)) +
  geom_bar()

# Ok, but cleaerer when separating histograms by facet_wrap(~sex).

#######################################################

# (e) Compute 2 new variables that signal and distinguish between 2 types of outliers in terms of height:

#outliers relative to the height of the overall sample (i.e., individuals with height values deviating more than 2 SD from the overall mean of height) 
(data_overall <- data %>%
  mutate(sd = sd(height, na.rm = TRUE),
         outliers = sd > 2, na.rm = TRUE))

#outliers relative to the height of some subgroup's mean and SD. Here, a suitable subgroup to consider is every person's gender (i.e., individuals with height values deviating more than 2 SD from the mean height of their own gender). 
(data_gender <- data %>%
  group_by(sex) %>%
  mutate(sd_gender = sd(height, na.rm = TRUE),
         outliers_gender = sd > 2, na.rm = TRUE))  # What is sd here?

# Good start, but simpler when combining multiple mutate steps in 1 pipe:
data_out <- data %>%      
  # 1. Compute means, SD, and outliers for overall sample: 
  mutate(mn_height  = mean(height, na.rm = TRUE),  
         sd_height  = sd(height, na.rm = TRUE),
         out_height = abs(height - mn_height) > (crit * sd_height)) %>%
  group_by(sex) %>%       
  # 2. Compute same metrics for subgroups (by sex):
  mutate(mn_sex_height  = mean(height, na.rm = TRUE), 
         sd_sex_height  = sd(height, na.rm = TRUE),
         out_sex_height = abs(height - mn_sex_height) > (crit * sd_sex_height))

data_out

##################################################

#(f) Use the 2 new variables to define and identify 2 subgroups of people:

  #out_1: Individuals (females and males) with height values that are outliers relative to both the entire sample and the sample of their own gender. How many such individuals are in data? (1 point)

  #out_2: Individuals (females and males) with height values that are not outliers relative to the entire population, but are outliers relative to their own gender. How many such individuals are in data? (1 point)

pt <- (pt + 6) # good start.
```

<!-- ## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ## --> 

Total of 38 points (out of 50).
Grade: 1.0.  Congratulations! 

<!-- ## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ## 
## End of file. ----- --> 